#!/usr/bin/env php
<?php

/**
 * @file
 * Main entry point for the application.
 */

declare(strict_types=1);

use Symfony\Component\Console\Application;
use YourNamespace\App\Command\JokeCommand;
use YourNamespace\App\Command\SayHelloCommand;

foreach ([
  $GLOBALS['_composer_autoload_path'] ?? NULL,
  __DIR__ . '/../../autoload.php',
  __DIR__ . '/../vendor/autoload.php',
  __DIR__ . '/vendor/autoload.php',
] as $file) {
  if (is_string($file) && file_exists($file)) {
    require_once $file;
    unset($file);
    break;
  }
}

// @codeCoverageIgnoreStart
$application = new Application('Yourproject', '@yourproject-version@');

$command = new JokeCommand();
$application->add($command);
$application->setDefaultCommand((string) $command->getName());

$command = new SayHelloCommand();
$application->add($command);

$application->run();
// @codeCoverageIgnoreEnd
