name: Release docs

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  release-docs:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.base_url }}

    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v5

      - name: Install dependencies
        run: npm install
        working-directory: '${{ github.workspace }}/docs'

      - name: Build documentation site
        run: npm run build
        working-directory: '${{ github.workspace }}/docs'

      - name: Setup GitHub pages
        uses: actions/configure-pages@v5
        id: pages

      # Uncomment the following lines to deploy the documentation site.
      # - name: Upload documentation site
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: "docs/build"
      #
      # - name: Deploy documentation site
      #   uses: actions/deploy-pages@v4
